#ifndef AREAPLANMANAGER_GLOBAL_H
#define AREAPLANMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(AREAPLANMANAGER_LIBRARY)
#  define AREAPLANMANAGER_EXPORT Q_DECL_EXPORT
#else
#  define AREAPLANMANAGER_EXPORT Q_DECL_IMPORT
#endif

#endif // AREAPLANMANAGER_GLOBAL_H
