#ifndef PROCESSSIMULATION_GLOBAL_H
#define PROCESSSIMULATION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PROCESSSIMULATION_LIBRARY)
#  define PROCESSSIMULATION_EXPORT Q_DECL_EXPORT
#else
#  define PROCESSSIMULATION_EXPORT Q_DECL_IMPORT
#endif

#endif // PROCESSSIMULATION_GLOBAL_H
