#ifndef OSGEXTERN_GLOBAL_HEADER_H
#define OSGEXTERN_GLOBAL_HEADER_H

#include<NoQt.h>

#if defined(OSGEXTERN_LIBRARY)
#  define OSGEXTERNSHARED_EXPORT Q_DECL_EXPORT
#else
#  define OSGEXTERNSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // OSGEXTERN_GLOBAL_HEADER_H
