#ifndef SCENE_CORE_GLOBAL_H
#define SCENE_CORE_GLOBAL_H
#include <NoQt.h>

#if defined(SCENECORE_LIBRARY)
#  define SCENECORESHARED_EXPORT Q_DECL_EXPORT
#else
#  define SCENECORESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SCENCECORE_GLOBAL_H
