#ifndef EXTERNMAPSHAPE_GLOBAL_H
#define EXTERNMAPSHAPE_GLOBAL_H
#include <NoQt.h>

#if defined(EXTERNMAPSHAPE_LIBRARY)
#  define OSGEXTERNSHARED_EXPORT Q_DECL_EXPORT
#else
#  define OSGEXTERNSHARED_EXPORT Q_DECL_IMPORT
#endif
#endif // EXTERNMAPSHAPE_GLOBAL_H
