#ifndef SCENARIOMANAGER_GLOBAL_H
#define SCENARIOMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SCENARIOMANAGER_LIBRARY)
#  define SCENARIOMANAGER_EXPORT Q_DECL_EXPORT
#else
#  define SCENARIOMANAGER_EXPORT Q_DECL_IMPORT
#endif

#endif // SCENARIOMANAGER_GLOBAL_H
